mhn/__init__.py
from urllib.parse import urljoin

from flask import Flask, request, jsonify, abort, url_for, session
from flask_sqlalchemy import SQLAlchemy
from flask_security import Security, SQLAlchemyUserDatastore
from flask_security.utils import hash_password as hash
from flask_mail import Mail
from werkzeug.contrib.atom import AtomFeed
import xmltodict
import uuid
import random
import string
from flask_wtf.csrf import CsrfProtect
import os
import re

csrf = CsrfProtect()

db = SQLAlchemy()
# After defining `db`, import auth models due to
# circular dependency.
from mhn.auth.models import User, Role, ApiKey

user_datastore = SQLAlchemyUserDatastore(db, User, Role)

mhn = Flask(__name__)
mhn.config.from_object('config')
csrf.init_app(mhn)

# Email app setup.
mail = Mail()
mail.init_app(mhn)

# Registering app on db instance.
db.init_app(mhn)

# Setup flask-security for auth.
Security(mhn, user_datastore)

# Registering blueprints.
from mhn.api.views import api

mhn.register_blueprint(api)

from mhn.ui.views import ui

mhn.register_blueprint(ui)

from mhn.auth.views import auth

mhn.register_blueprint(auth)

# Trigger templatetag register.
from mhn.common.templatetags import format_date

mhn.jinja_env.filters['fdate'] = format_date

from mhn.auth.contextprocessors import user_ctx

mhn.context_processor(user_ctx)

from mhn.common.contextprocessors import config_ctx

mhn.context_processor(config_ctx)

import logging
from logging.handlers import RotatingFileHandler

mhn.logger.setLevel(logging.INFO)
formatter = logging.Formatter(
    '%(asctime)s -  %(pathname)s - %(message)s')
handler = RotatingFileHandler(
    mhn.config['LOG_FILE_PATH'], maxBytes=10240, backupCount=5, encoding='utf8')
handler.setLevel(logging.INFO)
handler.setFormatter(formatter)
mhn.logger.addHandler(handler)
if mhn.config['DEBUG']:
    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    console.setFormatter(formatter)
    mhn.logger.addHandler(console)


@mhn.route('/feed.json')
def json_feed():
    feed_content = get_feed().to_string()
    return jsonify(xmltodict.parse(feed_content))


@mhn.route('/feed.xml')
def xml_feed():
    return get_feed().get_response()


def makeurl(uri):
    baseurl = mhn.config['SERVER_BASE_URL']
    return urljoin(baseurl, uri)


def get_feed():
    from mhn.common.clio import Clio
    from mhn.auth import current_user
    authfeed = mhn.config['FEED_AUTH_REQUIRED']
    if authfeed and not current_user.is_authenticated():
        abort(404)
    feed = AtomFeed('MHN HpFeeds Report', feed_url=request.url,
                    url=request.url_root)
    sessions = Clio().session.get(options={'limit': 1000})
    for s in sessions:
        feedtext = u'Sensor "{identifier}" '
        feedtext += '{source_ip}:{source_port} on sensorip:{destination_port}.'
        feedtext = feedtext.format(**s.to_dict())
        feed.add('Feed', feedtext, content_type='text',
                 published=s.timestamp, updated=s.timestamp,
                 url=makeurl(url_for('api.get_session', session_id=str(s._id))))
    return feed


def create_clean_db():
    """
    Use from a python shell to create a fresh database.
    """
    with mhn.test_request_context():
        db.create_all()
        superuser = create_superuser_entry()

        from mhn.api.models import DeployScript
        # Creating a initial deploy scripts.
        deployscripts = {
            'Ubuntu - Conpot': os.path.abspath('./scripts/deploy_conpot.sh'),
            'Ubuntu - Dionaea': os.path.abspath('./scripts/deploy_dionaea.sh'),
            'Ubuntu - Cowrie': os.path.abspath('./scripts/deploy_cowrie.sh'),
            'Ubuntu - RDPHoney': os.path.abspath('./scripts/deploy_rdphoney.sh'),
            'Ubuntu - UHP': os.path.abspath('./scripts/deploy_uhp.sh'),
            'Ubuntu - Elasticpot': os.path.abspath('./scripts/deploy_elasticpot.sh')
        }
        for honeypot, deploypath in sorted(deployscripts.items()):
            with open(deploypath, 'r') as deployfile:
                initdeploy = DeployScript()
                initdeploy.script = deployfile.read()
                initdeploy.notes = 'Initial deploy script for {}'.format(honeypot)
                initdeploy.user = superuser
                initdeploy.name = honeypot
                db.session.add(initdeploy)

        db.session.commit()


def create_superuser_entry():
    # Creating superuser entry.
    superuser = user_datastore.create_user(
        email=mhn.config.get('SUPERUSER_EMAIL'),
        password=hash(mhn.config.get('SUPERUSER_ONETIME_PASSWORD')))
    adminrole = user_datastore.create_role(name='admin', description='')
    user_datastore.add_role_to_user(superuser, adminrole)
    user_datastore.create_role(name='user', description='')
    db.session.flush()

    apikey = ApiKey(user_id=superuser.id, api_key=str(uuid.uuid4()).replace("-", ""))
    db.session.add(apikey)
    db.session.flush()

    return superuser


def pretty_name(name):
    # remove trailing suffix
    nosuffix = os.path.splitext(name)[0]

    # remove special characters
    nospecial = re.sub('[\'";&%#@!()*]*', '', nosuffix)

    # Convert underscore to space
    underspace = re.sub('_', ' ', nospecial)

    return underspace


def reload_scripts():
    from mhn.api.models import DeployScript

    superuser = user_datastore.get_user(mhn.config.get('SUPERUSER_EMAIL'))
    custom_path = './custom_scripts/'

    deployscripts = {
        'Default - Conpot': os.path.abspath('./scripts/deploy_conpot.sh'),
        'Default - Dionaea': os.path.abspath('./scripts/deploy_dionaea.sh'),
        'Default - Cowrie': os.path.abspath('./scripts/deploy_cowrie.sh'),
        'Default - RDPHoney': os.path.abspath('./scripts/deploy_rdphoney.sh'),
        'Default - UHP': os.path.abspath('./scripts/deploy_uhp.sh'),
        'Default - Elasticpot': os.path.abspath('./scripts/deploy_elasticpot.sh')
    }

    f = []
    for (dirpath, dirnames, filenames) in os.walk(custom_path):
        f.extend(filenames)
        break
    for fname in f:
        p = os.path.abspath(custom_path + fname)
        if os.path.isfile(p):
            n = pretty_name(os.path.basename(p))
            deployscripts[n] = p

    db.session.query(DeployScript).delete()
    for honeypot, deploypath in sorted(deployscripts.items()):
        with open(deploypath, 'r') as deployfile:
            initdeploy = DeployScript()
            initdeploy.script = deployfile.read()
            initdeploy.notes = 'Initial deploy script for {}'.format(honeypot)
            initdeploy.user = superuser
            initdeploy.name = honeypot
            db.session.add(initdeploy)
            db.session.commit()

mhn/api/__init__.py
class APIModel(object):
    @classmethod
    def fields(cls):
        return cls.all_fields.keys()

    @classmethod
    def editable_fields(cls):
        return cls._make_field_list('editable')

    @classmethod
    def required_fields(cls):
        return cls._make_field_list('required')

    @classmethod
    def _make_field_list(cls, prop):
        """
        Returns a list of field names that have the property
        `prop` in the `all_fields` dictionary defined at
        class level.
        """
        return [f for f, e in cls.all_fields.items() if e.get(prop, False)]

    @classmethod
    def check_required(cls, payload):
        """
        Returns a list of required fields that are
        missing from the dictionary object `payload`.
        """
        missing = []
        for field in cls.required_fields():
            if (field not in payload) or payload.get(field) == '':
                missing.append(field)
        return missing

mhn/ui/views.py
from datetime import datetime, timedelta
from pygal.style import *
import pygal
from flask import (
        Blueprint, render_template, request, url_for,
        redirect, g)
from flask_security import logout_user as logout
import unicodedata
from sqlalchemy import desc, func

from mhn.ui.utils import get_flag_ip, get_country_ip, get_sensor_name
from mhn.api.models import (
        Sensor, DeployScript as Script)
from mhn.auth import login_required, current_user
from mhn.auth.models import User, PasswdReset, ApiKey
from mhn import db, mhn
from mhn.common.utils import (
        paginate_options, alchemy_pages, mongo_pages)
from mhn.common.clio import Clio

ui = Blueprint('ui', __name__, url_prefix='/ui')
from mhn import mhn as app

PYGAL_CONFIG = pygal.config.Config()
PYGAL_CONFIG.js = (
    'https://kozea.github.io/pygal.js/javascripts/svg.jquery.js',
    'https://kozea.github.io/pygal.js/javascripts/pygal-tooltips.js',
)

def remove_control_characters(s):
    return "".join(ch for ch in s if unicodedata.category(ch)[0]!="C")

@app.template_filter()
def number_format(value):
    return '{:,d}'.format(value)


@ui.before_request
def check_page():
    """
    Cleans up any query parameter that is used
    to build pagination.
    """
    try:
        page = int(request.args.get('page', 1))
    except ValueError:
        page = 1
    g.page = page


@ui.route('/login/', methods=['GET'])
def login_user():
    if current_user.is_authenticated():
        return redirect(url_for('ui.dashboard'))
    return render_template('security/login_user.html')


@mhn.route('/')
@ui.route('/dashboard/', methods=['GET'])
@login_required
def dashboard():
    clio = Clio()
    # Number of attacks in the last 24 hours.
    attackcount = clio.session.count(hours_ago=24)
    # TOP 5 attacker ips.
    top_attackers = clio.session.top_attackers(top=5, hours_ago=24)
    # TOP 5 attacked ports
    top_ports = clio.session.top_targeted_ports(top=5, hours_ago=24)
    # Top 5 honey pots with counts
    top_hp = clio.session.top_hp(top=5, hours_ago=24)
    # Top Honeypot sensors
    top_sensor = clio.session.top_sensor(top=5, hours_ago=24)
    # TOP 5 sigs
    freq_sigs = clio.hpfeed.top_sigs(top=5, hours_ago=24)
    return render_template('ui/dashboard.html',
                           attackcount=attackcount,
                           top_attackers=top_attackers,
                           top_ports=top_ports,
                           top_hp=top_hp,
                           top_sensor=top_sensor,
                           freq_sigs=freq_sigs,
                           get_sensor_name=get_sensor_name,
                           get_flag_ip=get_flag_ip,
                           get_country_ip=get_country_ip)


@ui.route('/attacks/', methods=['GET'])
@login_required
def get_attacks():
    clio = Clio()
    options = paginate_options(limit=10)
    options['order_by'] = '-timestamp'
    total = clio.session.count(**request.args.to_dict())
    sessions = clio.session.get(
            options=options, **request.args.to_dict())
    sessions = mongo_pages(sessions, total, limit=10)
    return render_template('ui/attacks.html', attacks=sessions,
                           sensors=Sensor.query, view='ui.get_attacks',
                           get_flag_ip=get_flag_ip, get_country_ip=get_country_ip,
                           get_sensor_name=get_sensor_name, **request.args.to_dict())


@ui.route('/feeds/', methods=['GET'])
@login_required
def get_feeds():
    clio = Clio()
    options = paginate_options(limit=10)
    options['order_by'] = '-_id'
    count, columns, feeds = clio.hpfeed.get_payloads(options, request.args.to_dict())
    channel_list = clio.hpfeed.channel_map.keys()
    feeds = mongo_pages(feeds, count, limit=10)
    return render_template('ui/feeds.html', feeds=feeds, columns=columns,
                           channel_list=channel_list, view='ui.get_feeds',
                           **request.args.to_dict())


@ui.route('/sensors/', methods=['GET'])
@login_required
def get_sensors():
    sensors = Sensor.query.all()
    total = Sensor.query.count()
    # Paginating the list.
    pag = paginate_options(limit=10)
    sensors = sensors[pag['skip']:pag['skip'] + pag['limit']]
    # Using mongo_pages because it expects paginated iterables.
    sensors = mongo_pages(sensors, total, limit=10)
    return render_template('ui/sensors.html', sensors=sensors,
                           view='ui.get_sensors', pag=pag)


@ui.route('/add-sensor/', methods=['GET'])
@login_required
def add_sensor():
    return render_template('ui/add-sensor.html')


@ui.route('/manage-deploy/', methods=['GET'])
@login_required
def deploy_mgmt():
    script_id = request.args.get('script_id')
    arch_id = request.args.get('arch_id')
    arch = ""
    if arch_id == "1":
        arch = "-arm"
    if not script_id or script_id == '0':
        script = Script(name='', notes='', script='')
    else:
        script = Script.query.get(script_id)
    return render_template(
            'ui/script.html', scripts=Script.query.order_by(Script.date.desc()),
            script=script, arch=arch)


@ui.route('/honeymap/', methods=['GET'])
@login_required
def honeymap():
    return render_template('ui/honeymap.html')


@ui.route('/add-user/', methods=['GET'])
@login_required
def settings():
    return render_template(
        'ui/settings.html', 
        users=User.query.filter_by(active=True),
        apikey=ApiKey.query.filter_by(user_id=current_user.id).first()
    )


@ui.route('/forgot-password/<hashstr>/', methods=['GET'])
def forgot_passwd(hashstr):
    logout()
    user = PasswdReset.query.filter_by(hashstr=hashstr).first().user
    return render_template('ui/reset-password.html', reset_user=user,
                           hashstr=hashstr)


@ui.route('/reset-password/', methods=['GET'])
def reset_passwd():
    return render_template('ui/reset-request.html')


def get_credentials_payloads(clio):
    credentials_payloads = []
    credentials_payloads += clio.hpfeed.get_payloads({'limit': 10000}, {"channel": "kippo.sessions"})[2]
    credentials_payloads += clio.hpfeed.get_payloads({'limit': 10000}, {"channel": "cowrie.sessions"})[2]
    return credentials_payloads


@app.route('/image/top_passwords.svg')
@login_required
def graph_passwords():
    clio = Clio()
    
    bar_chart = pygal.Bar(style=LightColorizedStyle, show_x_labels=True, config=PYGAL_CONFIG)
    bar_chart.title = "Kippo/Cowrie Top Passwords"
    clio = Clio()
    top_passwords = clio.hpfeed.count_passwords(get_credentials_payloads(clio))
    for password_data in top_passwords:
        password,count = password_data
        password = remove_control_characters(password)
        bar_chart.add(password, [{'label': password, 'xlink': '', 'value':count}])

    return bar_chart.render_response()


@app.route('/image/top_users.svg')
@login_required
def graph_users():
    clio = Clio()
    
    bar_chart = pygal.Bar(style=LightColorizedStyle, show_x_labels=True, config=PYGAL_CONFIG)
    bar_chart.title = "Kippo/Cowrie Top Users"
    clio = Clio()
    top_users = clio.hpfeed.count_users(get_credentials_payloads(clio))
    for user_list in top_users:
        user,password = user_list
        user = remove_control_characters(user)
        bar_chart.add(user, [{'label':user, 'xlink':'', 'value':password}])

    return bar_chart.render_response()


@app.route('/image/top_combos.svg')
@login_required
def graph_combos():
    clio = Clio()
    
    bar_chart = pygal.Bar(style=LightColorizedStyle, show_x_labels=True, config=PYGAL_CONFIG)
    bar_chart.title = "Kippo/Cowrie Top User/Passwords"
    clio = Clio()
    top_combos = clio.hpfeed.count_combos(get_credentials_payloads(clio))
    for combo_list in top_combos:
        user,password = combo_list
        user = remove_control_characters(user)
        bar_chart.add(user,[{'label':user,'xlink': '', 'value':password}])

    return bar_chart.render_response()


def top_kippo_cowrie_attackers(clio):
    top_attackers = []
    top_attackers += clio.session._tops('source_ip', 10, honeypot='kippo')
    top_attackers += clio.session._tops('source_ip', 10, honeypot='cowrie')

    import collections
    grouped = collections.Counter()
    for attacker in top_attackers:
        grouped[attacker['source_ip']] += int(attacker['count'])
    return [{'source_ip': ip, 'count': count} for ip, count in sorted(grouped.items(),
                                                                      key=lambda x: x[1], reverse=True)]

@app.route('/image/top_sessions.svg')
@login_required
def graph_top_attackers():
    clio = Clio()
    
    bar_chart = pygal.Bar(style=LightColorizedStyle, show_x_labels=True, config=PYGAL_CONFIG)
    bar_chart.title = "Kippo/Cowrie Top Attackers"
    clio = Clio()
    top_attackers = top_kippo_cowrie_attackers(clio)
    print(top_attackers)
    for attacker in top_attackers:
        bar_chart.add(str(attacker['source_ip']), attacker['count'])

    return bar_chart.render_response()


@ui.route('/chart')
def chart():
    return render_template('ui/chart.html')

mhn/templates/base.html
<!doctype html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <title>{% block extra_head %}{% endblock %}</title>
	<script type=text/javascript>
    		$SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
  	</script>
        <script src="{{ url_for('static', filename='js/vendor/jquery.js') }}"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/foundation.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
        <script src="{{ url_for('static', filename='js/vendor/foundation.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/vendor/modernizr.js') }}"></script>
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </head>
    <body>
        {% if user.is_authenticated %}
        <nav class="top-bar" style="margin-bottom: 30px;"  data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="{{ url_for('ui.dashboard') }}">CHN Server</a></h1>
                </li>
            </ul>
            <section class="top-bar-section">
                <!-- Left Nav Section -->
                <ul class="left">
                    <li><a href="{{ url_for('ui.deploy_mgmt') }}">Deploy</a></li>
                    <li><a href="{{ url_for('ui.get_attacks') }}">Attacks</a></li>
                    <li><a href="{{ url_for('ui.get_feeds', channel='dionaea.capture') }}">Payloads</a></li>
                    <li class="has-dropdown">
                        <a href="{{ url_for('ui.get_sensors') }}">Sensors</a>
                        <ul class="dropdown">
                            <li><a href="{{ url_for('ui.get_sensors') }}">View sensors</a></li>
                            <li><a href="{{ url_for('ui.add_sensor') }}">Add sensor</a></li>
                        </ul>
                    </li>
            
				
				
			 <li class="has-dropdown">
                        <a href="{{ url_for('ui.chart') }}">Charts</a>
                        <ul class="dropdown">
			    <li><a href="{{ url_for('graph_passwords') }}">Kippo/Cowrie Top Passwords</a></li>
                            <li><a href="{{ url_for('graph_users') }}">Kippo/Cowrie Top Users</a></li>
                            <li><a href="{{ url_for('graph_combos') }}">Kippo/Cowrie Top User/Passwords</a></li>
                            <li><a href="{{ url_for('graph_top_attackers') }}">Kippo/Cowrie Top Attackers</a></li>
                        </ul>
                    </li>
                </ul>

				
				
				
                <!-- Right Nav Section -->
                <ul class="right">
                    <li class="active"><a id="out-btn" href="#">LOGOUT</a></li>
                </ul>
                {% if current_user.has_role('admin') %}
                <ul class="right">
                    <li class=""><a id="out-btn" href="{{ url_for('ui.settings') }}">Settings</a></li>
                </ul>
                {% endif %}
            </section>
        </nav>
        {% endif %}
        {% block content %}{% endblock %}
        {% block footer %}
        <style>
            #footer {
                margin-top: 80px;
                margin-bottom: 80px;
                bottom: 0;
                width: 100%;
            }
        </style>
        <div class="row" id="footer">
            <div class="small-7 large-centered columns">
              <span><small><a href="https://github.com/CommunityHoneyNetwork">CommunityHoneyNetwork is an open source project!</a></small><span>
            </div>
        </div>
        {% endblock %}
        <script src="{{ url_for('static', filename='js/vendor/fastclick.js') }}"></script>
        <script>
            $(document).foundation();
        </script>
    </body>
</html>

mhn/templates/pagination.html
{% macro render_pagination(items, view, args) %}
{% if items.pages > 1 %}
<div class="pagination-centered">
    <ul class="pagination">
        {% if items.page > 1 %}
        {% set _ = args.update({'page': items.page - 1}) %}
        <li class="arrow"><a href="{{ url_for(view, **args) }}">&laquo;</a></li>
        {% endif %}
        {% for page in items.iter_pages() %}
        {% if not page %}
        <li class="unavailable" style="color:#999;">&hellip;</li>
        {% else %}
        {% set _ = args.update({'page': page}) %}
        <li class={% if page == items.page %}"current"{% endif %}>
            <a href="{{ url_for(view, **args) }}">{{ page }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if items.pages > items.page %}
        {% set _ = args.update({'page': items.page + 1}) %}
        <li class="arrow"><a href="{{ url_for(view, **args) }}">&raquo;</a></li>
        {% endif %}
    </ul>
</div>
{% endif %}
{% endmacro %}